apiVersion: v1
kind: Pod
metadata:
  name: mount-dev
  namespace: mount-log
spec:
  serviceAccountName: logger
  containers:
  - name: escaper
    image: ubuntu
    volumeMounts:
    - name: logs
      mountPath: /var/log/host
  volumes:
  - name: logs
    hostPath:
      path: /var/log/
      type: Directory